### ISSUE TITLE
bootloader

### ISSUE THREAD

**Issue by gelius1959** [darkspr1te/RD60xx_Test_code#2]
Checked  RD60xx_Test_code it works fine
An excellent program for repairing a damaged device.
 RD60012-Bootloader-v1.10.bin.zip doesn't work for RD6006 
Or I'm not doing it right, what are your recommendations, how can you help.
It is a pity for the damaged device, which does not work only because of the lack of a program

**Comment by darkspr1te** [comment]
to use the rd6006/12 bootloader you need to flash using SWD via st-flash , erase first then flash. what errors, issues are you seeing ? as far as i know from the eevblog discussions the 06/12 models are identical in design but 12 models has larger mosfets, 
does the unit boot/show any display ?

**Comment by gelius1959** [comment]
Yes I downloaded using Stlink v2 (SWD) Serial3 not conect, LCD not worcing

**Comment by gelius1959** [comment]
Errors when writing, through SWD no

**Comment by gelius1959** [comment]
Maybe this is due to the fact that I do STM8 not have  on the board PWR

**Comment by darkspr1te** [comment]
one test you can try is using the official stmflash tool is write the bootloader to 0x0000 and then write the flash upgrade file file to 0x6000, you will have to decrypt and  remove the header from the update file first before writing , see this post for guide https://www.eevblog.com/forum/microcontrollers/rd60xx-mcu-controlled-power-units/msg3637822/#msg3637822 (post #10) 
i've not diassembled my unit so i dont know how it functions when not fully assembled so some factors may block booting if the system cant see it (eg the stm8)

**Comment by gelius1959** [comment]
Ok I'll work, it's already interesting.
I love to tinker, where not everything is simple:))
I can still contact you for advice??

**Comment by gelius1959** [comment]
![изображение_viber_2022-11-25_19-05-40-557](https://user-images.githubusercontent.com/66623172/204034157-5488c8ad-d93f-4737-af87-9d881efa155f.jpg)
![изображение_viber_2022-11-25_19-06-04-450](https://user-images.githubusercontent.com/66623172/204034196-6ac94596-6d74-45af-b9ec-f10ddebb46fe.jpg)

**Comment by darkspr1te** [comment]
yes, can we continue via EEV blog forum where you have already posted. I can already see one issue, no calibration & checksum values nor lcd model,  not sure how to fix that right now short of getting a backup from another user or trying my rd6012 values instead

**Comment by gelius1959** [comment]
Okay, I'll be glad to any of your advice.
I'm more of an electronics engineer than a programmer.:))
But I still understand something, and I can continue work

**Comment by darkspr1te** [comment]
I have posted Further info  to the eevblog forum.

**Comment by gelius1959** [comment]
Hello darkspr1te
All my attempts to restore the device rd6006 have failed.
I can not understand the following, what does the phrase mean
 **“write the bootloader to 0x0000 and then write the flash upgrade file file to 0x6000,”**
After all, flash memory banks in the controller STM32 begin with the address 0х0800 0000
 **"You can change the BOOTx pins to change whether is boots from different addresses, ie FLASH (0x08000000), ROM (0x1FFFF000) or RAM (0x20000000)"**
![2022-11-28](https://user-images.githubusercontent.com/66623172/204210496-385ca327-b6eb-4621-9dee-779784da9203.png)
![c10f2d](https://user-images.githubusercontent.com/66623172/204239196-6ae025f8-216e-4239-bd66-a9fa201836ea.png)

Explain in more detail how you program to address 0x0000
I have experience with STM32, but I don't understand how to do it
TtsIf it's not difficult for you, then step by step, if it's not difficult for you, then insert pictures.
I'm already confused, maybe I'm doing it wrong. And that's the whole reason :(

**Comment by darkspr1te** [comment]
0x00000 is same as 0x08000000 and 0x6000 is 0x08006000 , it's just aliased memory . the flash upgrade file has to be the decrypted file without header. 
darkspr1te

**Comment by gelius1959** [comment]
Ok now I understand, I will continue to look for a solution.:)

But still, I hope you finish the open-RD60012-Bootloader project.

**Comment by gelius1959** [comment]
> 0x08006000

**Comment by gelius1959** [comment]
> 
I also checked this option.
 "**write the bootloader to 0x0000 and then write the flash upgrade file file to 0x6000,** "
Unfortunately, the bootloader "**RD60012-Bootloader-v1.10.bin.zip**" does not work
I'm sorry, I'm not distracting you, I think you are busy enough with your work.
If yes then excuse me
